# Generated by Django 5.1 on 2024-09-01 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('speciality', models.TextField()),
                ('degree', models.TextField()),
                ('intro', models.TextField()),
                ('complete', models.TextField()),
                ('end', models.TextField()),
            ],
        ),
    ]
