# Generated by Django 5.1 on 2024-09-05 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LANS_HOSPITAL_APP', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room_rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_type', models.TextField()),
                ('charge', models.TextField()),
            ],
        ),
    ]
