# Generated by Django 5.1 on 2024-09-07 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LANS_HOSPITAL_APP', '0002_doctor_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='appointment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='time',
            field=models.TextField(blank=True, null=True),
        ),
    ]
