# Generated by Django 5.1 on 2024-09-05 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LANS_HOSPITAL_APP', '0002_room_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_type', models.CharField(max_length=100)),
                ('charge', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.DeleteModel(
            name='Room_rate',
        ),
    ]
