# Generated by Django 5.1 on 2024-09-07 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LANS_HOSPITAL_APP', '0003_doctor_appointment_doctor_fee_doctor_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('data', models.CharField(max_length=100)),
                ('time', models.CharField(max_length=100)),
                ('message', models.TextField()),
            ],
        ),
    ]
