# Generated by Django 5.1 on 2024-09-07 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LANS_HOSPITAL_APP', '0004_appointment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='data',
            new_name='date',
        ),
    ]
