# Generated by Django 5.1 on 2024-09-07 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LANS_HOSPITAL_APP', '0005_rename_data_appointment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='doctor_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
